import { promises as fs } from "node:fs";
import path from "node:path";
import { listHostEventMethods, type HostServiceTypeName } from "./registry";
import { loadModuleExport, relativeImport, sourcePathForHeader } from "./common";

function asTypeName(type: HostServiceTypeName): string {
  switch (type) {
    case "string":
      return "string";
    case "bool":
      return "bool";
    case "i32":
      return "i32";
    case "u32":
      return "u32";
    case "i64":
      return "i64";
    case "u64":
      return "u64";
    case "f64":
      return "f64";
    case "bytes":
      return "Uint8Array";
    case "i32_array":
      return "Int32Array";
    case "u32_array":
      return "Uint32Array";
    case "i64_array":
      return "Int64Array";
    case "u64_array":
      return "Uint64Array";
    case "f64_array":
      return "Float64Array";
    case "void":
      return "void";
  }
}

function callbackTypeFor(argTypes: readonly HostServiceTypeName[]): string {
  if (argTypes.length === 0) {
    return "Callback0";
  }
  if (argTypes.length === 1) {
    return `Callback1<${asTypeName(argTypes[0])}>`;
  }
  if (argTypes.length === 2) {
    return `Callback2<${asTypeName(argTypes[0])}, ${asTypeName(argTypes[1])}>`;
  }
  throw new Error(`Host event uses ${String(argTypes.length)} args; only 0-2 are supported right now.`);
}

function emitExportArgs(argTypes: readonly HostServiceTypeName[]): string {
  const parts: string[] = [];
  argTypes.forEach((type, index) => {
    if (
      type === "string" ||
      type === "bytes" ||
      type === "i32_array" ||
      type === "u32_array" ||
      type === "i64_array" ||
      type === "u64_array" ||
      type === "f64_array"
    ) {
      parts.push(`arg${String(index)}Ptr: usize`, `arg${String(index)}Len: u32`);
      return;
    }
    parts.push(`arg${String(index)}: ${asTypeName(type)}`);
  });
  return parts.join(", ");
}

function emitDecodedArgs(argTypes: readonly HostServiceTypeName[]): string[] {
  const lines: string[] = [];
  argTypes.forEach((type, index) => {
    if (type === "string") {
      lines.push(
        `  const arg${String(index)} = arg${String(index)}Len == 0 ? "" : String.UTF8.decodeUnsafe(arg${String(index)}Ptr, <usize>arg${String(index)}Len, false);`,
      );
      return;
    }
    if (type === "bytes") {
      lines.push(`  const arg${String(index)} = new Uint8Array(<i32>arg${String(index)}Len);`);
      lines.push(`  if (arg${String(index)}Len > 0) {`);
      lines.push(`    memory.copy(arg${String(index)}.dataStart, arg${String(index)}Ptr, <usize>arg${String(index)}Len);`);
      lines.push("  }");
      return;
    }
    if (type === "i32_array" || type === "u32_array") {
      const arrayType = type === "i32_array" ? "Int32Array" : "Uint32Array";
      lines.push(`  const arg${String(index)} = new ${arrayType}(<i32>arg${String(index)}Len);`);
      lines.push(`  if (arg${String(index)}Len > 0) {`);
      lines.push(`    memory.copy(arg${String(index)}.dataStart, arg${String(index)}Ptr, <usize>arg${String(index)}Len << 2);`);
      lines.push("  }");
      return;
    }
    if (type === "i64_array" || type === "u64_array" || type === "f64_array") {
      const arrayType =
        type === "i64_array" ? "Int64Array" : type === "u64_array" ? "Uint64Array" : "Float64Array";
      lines.push(`  const arg${String(index)} = new ${arrayType}(<i32>arg${String(index)}Len);`);
      lines.push(`  if (arg${String(index)}Len > 0) {`);
      lines.push(`    memory.copy(arg${String(index)}.dataStart, arg${String(index)}Ptr, <usize>arg${String(index)}Len << 3);`);
      lines.push("  }");
      return;
    }
  });
  return lines;
}

export async function generateAssemblyScriptHostEventsFile(
  modulePath: string,
  exportName: string,
  outputPath: string,
  primitivesImportOverride: string | undefined,
): Promise<void> {
  const registry = await loadModuleExport(modulePath, exportName, "fui-host-events-");
  const methods = listHostEventMethods(registry as never);
  const callbackImport =
    primitivesImportOverride ??
    relativeImport(outputPath, path.resolve(path.dirname(modulePath), "..", "..", "src/FuiPrimitives.ts"));
  const blocks: string[] = [
    "// @ts-nocheck",
    `// Generated by hostgen from ${sourcePathForHeader(modulePath)}#${exportName}.`,
    `import { Callback0, Callback1, Callback2 } from "${callbackImport}";`,
    "",
  ];
  methods.forEach((method, index) => {
    const callbackType = callbackTypeFor(method.args);
    const exportArgs = emitExportArgs(method.args);
    const decodedArgs = emitDecodedArgs(method.args);
    const publicName =
      method.eventName.length === 0
        ? method.eventName
        : `${method.eventName.charAt(0).toUpperCase()}${method.eventName.slice(1)}`;
    blocks.push(`let __${method.eventName}Handler: ${callbackType} | null = null;`);
    blocks.push("");
    blocks.push(`export function on${publicName}(callback: ${callbackType} | null): void {`);
    blocks.push(`  __${method.eventName}Handler = callback;`);
    blocks.push("}");
    blocks.push("");
    blocks.push(`export function clear${publicName}(): void {`);
    blocks.push(`  __${method.eventName}Handler = null;`);
    blocks.push("}");
    blocks.push("");
    blocks.push(`export function ${method.exportName}(${exportArgs}): void {`);
    blocks.push(`  const callback = __${method.eventName}Handler;`);
    blocks.push("  if (callback === null) {");
    blocks.push("    return;");
    blocks.push("  }");
    blocks.push(...decodedArgs);
    if (method.args.length === 0) {
      blocks.push("  callback.invoke();");
    } else {
      blocks.push(
        `  callback.invoke(${method.args.map((_type, index) => `arg${String(index)}`).join(", ")});`,
      );
    }
    blocks.push("}");
    if (index + 1 < methods.length) {
      blocks.push("");
      blocks.push("");
    }
  });
  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, `${blocks.join("\n")}\n`, "utf8");
}
